CREATE TABLE catalog_entry (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         VARCHAR(10)   NOT NULL CHECK (type IN ('BOOK', 'FILM', 'ALBUM')),
    title        VARCHAR(200)  NOT NULL,
    creator      VARCHAR(200)  NOT NULL,
    release_year INTEGER       CHECK (release_year BETWEEN 1000 AND 2100),
    description  VARCHAR(2000),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

-- One row once the demo fixtures have been loaded into a new database, so an
-- emptied catalog is not silently re-seeded on the next restart.
CREATE TABLE demo_seed (
    id        INTEGER PRIMARY KEY CHECK (id = 1),
    seeded_at TIMESTAMP WITH TIME ZONE NOT NULL
);
